services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Volumen para persistir los datos

  app:
    image: raulagras/app:latest  # Aquí especificamos la imagen en lugar de construirla
    container_name: app
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongodb_data:
