services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    depends_on:
      - mongodb
    networks:
      - app_network
    environment:
      - MONGO_URI=mongodb://mongodb:27017

networks:
  app_network:

volumes:
  mongodb_data:
